// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyCookbook.API;

#nullable disable

namespace MyCookbook.API.Migrations
{
    [DbContext(typeof(MyCookbookContext))]
    [Migration("20231010041447_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("IngredientRecipe", b =>
                {
                    b.Property<Guid>("IngredientsGuid")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipesGuid")
                        .HasColumnType("TEXT");

                    b.HasKey("IngredientsGuid", "RecipesGuid");

                    b.HasIndex("RecipesGuid");

                    b.ToTable("IngredientRecipe");
                });

            modelBuilder.Entity("MyCookbook.API.Author", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserGuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("UserGuid");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("MyCookbook.API.Ingredient", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("MyCookbook.API.Recipe", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuthorGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TotalTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("AuthorGuid");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("MyCookbook.API.RecipeUrl", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<string>("LdJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessingStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.ToTable("RecipeUrls");
                });

            modelBuilder.Entity("MyCookbook.API.User", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IngredientRecipe", b =>
                {
                    b.HasOne("MyCookbook.API.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyCookbook.API.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyCookbook.API.Author", b =>
                {
                    b.HasOne("MyCookbook.API.User", "User")
                        .WithMany()
                        .HasForeignKey("UserGuid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyCookbook.API.Recipe", b =>
                {
                    b.HasOne("MyCookbook.API.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorGuid");

                    b.Navigation("Author");
                });
#pragma warning restore 612, 618
        }
    }
}
